#!/bin/bash

MOAB_INSTALL_PATH=/clinic/2015/sandia15/max/moabInstall
# change this path to be the path to your local, non-bare clone of the moab.git repository at /clinic/2015/sandia15/source/moab.git
# if you cloned the moab.git repo to ~/moab, this would be /home/<username>/moab
MOAB_SRC_PATH=/clinic/2015/sandia15/max/moab
MPI_PATH=/clinic/2015/sandia15/mpich-3.1.4 #pi mpi!
PYTHON_PATH=/clinic/2015/sandia15/Python-2.7.10
CGAL_PATH=/clinic/2015/sandia15/CGAL-4.6.3
TRILINOS_PATH=/clinic/2015/sandia15/trilinos-11.14.3
STLIB_PATH=/clinic/2015/sandia15/source/stlib
OUR_PATH=/clinic/2015/sandia15/max/hmc-tessellate # please note that "tessellate" contains 2 "l"s.
EXTRA_ARGS=$@

cmake \
      -D CMAKE_BUILD_TYPE:STRING=RELEASE \
      -D CMAKE_Python_CREATE_SHARED_LIBRARY:STRING="ON" \
      -D BUILD_SHARED_LIBS:STRING="ON" \
      -D TPL_ENABLE_MPI:BOOL=ON \
      -D MPI_BASE_DIR:PATH="$MPI_PATH"\
      -D MPI_BIN_DIR:PATH="$MPI_PATH/bin"\
      -D MPI_INCLUDE_PATH:PATH="$MPI_PATH/include" \
      -D MPI_USE_COMPILER_WRAPPERS:BOOL=ON \
      -D MPI_Fortran_COMPILER:FILEPATH="$MPI_PATH/bin/mpif90" \
      -D MPI_CXX_COMPILER:FILEPATH="$MPI_PATH/bin/mpicxx" \
      -D MPI_C_COMPILER:FILEPATH="$MPI_PATH/bin/mpicc" \
      -D MPI_EXEC:FILEPATH="$MPI_PATH/bin/mpiexec" \
      -D CMAKE_Fortran_FLAGS:STRING="-O3 -Wall" \
      -D CMAKE_Python_COMPILER:FILEPATH="${PYTHON_PATH}/bin/python2.7" \
      -D PYTHON_EXECUTABLE:FILEPATH="${PYTHON_PATH}/bin/python2.7" \
      -D PYTHON_INCLUDE_DIR:PATH="${PYTHON_PATH}/include/python2.7" \
      -D PYTHON_LIBRARY:FILEPATH="${PYTHON_PATH}/lib/libpython2.7.dylib" \
      -D CMAKE_CXX_FLAGS:STRING="-std=gnu++11 -DBASIC_CYCLIC_MANAGER_DEFAULT_PAST_STATES=5 -D_TRILINOS118 -D_PUBLICTRILINOS -DKOKKOS_IS_CLASSIC -fPIC -lgmp -lmpfr" \
      -D moab_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
      -D moab_ENABLE_MeshLess:BOOL=TRUE \
      -D moab_ENABLE_KernelPrototypes:BOOL=TRUE \
      -D moab_ENABLE_Core:BOOL=TRUE \
      -D moab_ENABLE_Kernels:BOOL=TRUE \
      -D moab_ENABLE_Neighbors:BOOL=TRUE \
      -D moab_ENABLE_Fields:BOOL=TRUE \
      -D moab_ENABLE_Operators:BOOL=TRUE \
      -D moab_ENABLE_Equations:BOOL=TRUE \
      -D moab_ENABLE_VoroInterface:BOOL=TRUE \
      -D moab_ENABLE_ParticleMotion:BOOL=TRUE \
      -D moab_ENABLE_TESTS:BOOL="ON" \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
      -D CMAKE_INSTALL_PREFIX:PATH="${MOAB_INSTALL_PATH}" \
      -D ForTrilinos_DISABLE_DEFERRED_LENGTH_CHARACTERS:BOOL=TRUE \
	  -D TPL_ENABLE_Voro++:STRING='ON' \
      -D TPL_ENABLE_CGAL:STRING='OFF' \
      -D TPL_ENABLE_STLIB:STRING='ON' \
      -D TPL_STLIB_INCLUDE_DIRS:FILEPATH="${STLIB_PATH}" \
      -D TPL_STLIB_LIBRARY_DIRS:FILEPATH="${STLIB_PATH}" \
      -D TPL_STLIB_LIBRARIES:FILEPATH="${STLIB_PATH}" \
	  -D Voro++_INCLUDE_DIRS:FILEPATH="${OUR_PATH}" \
	  -D Voro++_LIBRARY_DIRS:FILEPATH="${OUR_PATH}" \
      -D CGAL_LIBRARY_DIRS:FILEPATH="${CGAL_PATH}/lib" \
      -D CGAL_INCLUDE_DIRS:FILEPATH="${CGAL_PATH}/include" \
      -D TPL_CGAL_LIBRARIES:STRING="${CGAL_PATH}/lib/libCGAL.so;${CGAL_PATH}/lib/libCGAL_Core.so" \
      -D TPL_ENABLE_Trilinos:STRING='ON' \
      -D Trilinos_DIR="${TRILINOS_PATH}" \
      -D Trilinos_LIBRARY_DIRS:FILEPATH="${TRILINOS_PATH}/lib" \
      -D Trilinos_INCLUDE_DIRS:FILEPATH="${TRILINOS_PATH}/include" \
      ${EXTRA_ARGS} \
      ${MOAB_SRC_PATH}

#      -D CMAKE_CXX_LINK_EXECUTABLE="<CMAKE_CXX_COMPILER>  <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS>  -o <TARGET> -lamesos2 -lamesos2 -lifpack2-adapters -lkokkostsqr -lpamgen -lpamgen_extras -lteko -lthyratpetra <LINK_LIBRARIES> -lamesos2 -lifpack2-adapters -lkokkostsqr -lpamgen -lpamgen_extras -lteko -lthyratpetra -lamesos2" \
#      -D CMAKE_Python_COMPILER_ENV_VAR:STRING="python2.7" \
#      -D moab_ENABLE_ALL_PACKAGES:BOOL="ON" \
#-D CMAKE_Fortran_FLAGS:STRING="-O3 -Wall -fcoarray=single" \
#      -D CMAKE_CXX_FLAGS:STRING=" -std=gnu++11 -D_TRILINOS118" \
